### PR TITLE
Feature/ba 118 search page results

### PR DESCRIPTION
**Pull request by Braedencraig**
Pr contains desktop/mobile styled search page results and tab functionality

### CODE REVIEW

**Comment by Braedencraig** [comment]
Sounds good to me! Will update asap!

@kycapstick 
Also though, are we sure we want the "pages" tab, yeah? In the ticket assumptions its not there, but in the design it is but I can't remember if we axed that a week or two ago in meeting(s)? No prob to add it in though of course!

**Comment by kycapstick** [comment]
> Sounds good to me! Will update asap!
> 
> @kycapstick Also though, are we sure we want the "pages" tab, yeah? In the ticket assumptions its not there, but in the design it is but I can't remember if we axed that a week or two ago in meeting(s)? No prob to add it in though of course!

@Braedencraig I believe it was more of a naming issue for the client where they didn't like the name "Pages". I would definitely fight to keep it as it's a pretty essential functionality for a user to be able to search the site, not just the content. Especially since Publications and Blogs also have their own searches.

**Comment by Braedencraig** [comment]
@kycapstick Feedback addressed and tested! Should be good for review again!!

**Review by kycapstick — COMMENTED** [review]
Changes look good! Only thing I'm noticing is the container for the "Results" text is creating some weird spacing on the Publications page. Since it has padding top applied, even when it doesn't have content it's adding the spacing for it. It looks like it's also creating the spacing between the tags and the tabs on the Search Page. 
Screen Shot 2022-02-10 at 10 18 03 AM
Screen Shot 2022-02-10 at 10 18 23 AM

**Comment by kycapstick** [comment]
@Braedencraig one other thing. It looks like you've added in reload functionality when the query params are updated. I specifically wanted to avoid reloading the page as it closes the drawer with the tags on the Publications page. Which is why it triggers the click on the hidden refresh button.

**Comment by kycapstick** [comment]
Looking good! One last thing. On or around line 49 of page-publications you have the data-posttype hard coded as Publications, this is used when pulling in the results after filters are applied. It looks like you updated in the first instance to be the $id, can you update it here as well?

**Review by kycapstick — APPROVED** [review]

**Pull request merged**
