### PR TITLE
BA-397 add styling to news/researchblogs for custom video

### PR DESCRIPTION
**Pull request by Braedencraig**
This PR updates styling for the custom video component when used on the research-blog and/or news page(s)!

### CODE REVIEW

**Review by lisafolkerson — APPROVED** [review]
👶🏻 🎥

**Comment by lisafolkerson** [comment]
Screen Shot 2022-04-20 at 5 25 19 PM

Is this broken content ok?

**Comment by Braedencraig** [comment]
> Screen Shot 2022-04-20 at 5 25 19 PM
> 
> Is this broken content ok?

Yeah! Thats the core/video component, I removed it altogether, it should NOT be used. the Video block that should be used to include videos I implemented above that broken one, so you can see it working properly there! ALL is well!

**Comment by lisafolkerson** [comment]
> 

Merge away!

**Pull request merged**
